### ISSUE TITLE
4 warnings

### ISSUE THREAD

**Issue by pikachurus** [toteph42/identity_switch#41]
1.0.45:

> PHP Warning:  Undefined array key "flags" in /var/www/roundcubemail/plugins/identy_switch/identy_switch_prefs.php on line 684

> PHP Warning:  Undefined array key "label" in /var/www/roundcubemail/plugins/identy_switch/identy_switch_prefs.php on line 604

> PHP Warning:  Undefined array key "notify_timeout" in /var/www/roundcubemail/plugins/identy_switch/identy_switch_prefs.php on line 311

> PHP Warning:  Undefined array key "imap_pwd" in /var/www/roundcubemail/plugins/identy_switch/identy_switch_prefs.php on line 645

**Comment by toteph42** [comment]
Fixed in 1.0.1
