### ISSUE TITLE
Default label name

### ISSUE THREAD

**Issue by HostOncilla** [toteph42/identity_switch#42]
Is there a way to be able to also rename the default account label? At the moment it just used the display name set on identity but it would be nice to be able to rename it to something else, specially if you have multiple identities containing the same display name, it makes it real hard to distinguish between accounts when selecting on the switcher.

**Comment by toteph42** [comment]
If you specify a identity_switch label, then display name is ignored and the label is used in drop down menu. Only your default (standard) identity, for which you don't need to create an identity record, the display name is used.

**Comment by HostOncilla** [comment]
That's the one I was referring to, the default (standard) identity it would be handy if we could change that name.

**Comment by toteph42** [comment]
I do not understand your problem: Change display name of standard identity and you're done.

**Comment by HostOncilla** [comment]
I'm going to try and do a better job at explaining. All the other identities that's not default one, you can select a label name for them, so if you want to display email addresses you can. You don't have that option for the default identity as it just grabs the name from the display name. Of course you could change the display name and enter an email address there but then it will just look messy. All I'm trying to say is that would be nice if there was an option to also rename the default identity label and not just rely on the display name. At the moment you can have them all display with email addresses apart from the default identity.

Examples of what it would look like. 
![image](https://github.com/user-attachments/assets/db21afc0-6072-4c60-842c-3cc9e9708b35)

**Comment by toteph42** [comment]
You can change the display name to whatever you want. Only if you have disabled editing of that field in RoundCube configuration, then you can't the field. Check for something like `dont_override`  in `config.inc.php`.

**Comment by HostOncilla** [comment]
You are right you can but the problem with that is that it all gets very messy. Have a look at screenshots for examples.

Displaying with name on the display filed.
![image](https://github.com/user-attachments/assets/fe31efd5-efed-4fa5-9639-c8b0af0cb8d6)
![image](https://github.com/user-attachments/assets/2f554d7d-b15d-487d-b999-fdec7ecb20fd)
![image](https://github.com/user-attachments/assets/0f472b9f-add6-40ed-bc8e-066026429db5)

Displaying with email on the display filed.
![image](https://github.com/user-attachments/assets/095b9ab4-82f2-4870-bef6-5300f4911157)
![image](https://github.com/user-attachments/assets/7d98a808-87a8-40f4-8de2-67d7cd3eb311)
![image](https://github.com/user-attachments/assets/9816d21e-65c5-4a6a-9866-7949a726d1ae)

**Comment by HostOncilla** [comment]
Also, if you don't have a name on the "Display name" filed you then just get a bank selection on the drop-down.

![image](https://github.com/user-attachments/assets/7d15cad6-3eb8-44bb-992b-e4d2eeebc4c8)
![image](https://github.com/user-attachments/assets/bda08857-45ae-4143-86a5-157b9eb7136c)

**Comment by toteph42** [comment]
![grafik](https://github.com/user-attachments/assets/5bda1049-f428-43ae-8840-62fff73b4ea9)

**Comment by toteph42** [comment]
Fixed in 1.1.1
