### ISSUE TITLE
Undefined array key "debug"

### ISSUE THREAD

**Issue by pikachurus** [toteph42/identity_switch#45]
identity_switch 1.1.3

in config 'debug' = false:
> 2024/12/07 18:40:20 [error] 1619#1619: *36608 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "debug" in /var/www/roundcubemail/plugins/identity_switch/identity_switch_prefs.php on line 1246PHP message: PHP Warning:  Undefined array key "debug" in /var/www/roundcubemail/plugins/identity_switch/identity_switch_prefs.php on line 1246PHP message: PHP Warning:  Undefined array key "debug" in /var/www/roundcubemail/plugins/identity_switch/identity_switch_prefs.php on line 1246" while reading response header from upstream, client: 192.168.61.103, server: xxx.xxx, request: "POST /?_task=mail&_action=refresh HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "xxx.xxx", referrer: "https://xxx.xxx/?_task=mail&_mbox=INBOX"

with 'logging' = true:

> Undefined array key "logging" in /var/www/roundcubemail/plugins/identity_switch/identity_switch_newmails.php on line 61PHP message: PHP Warning:  Undefined array key "debug" in /var/www/roundcubemail/plugins/identity_switch/identity_switch_newmails.php on line 62PHP message: PHP Warning:  Undefined array key "retries" in /var/www/roundcubemail/plugins/identity_switch/identity_switch_newmails.php on line 111PHP message: PHP Warning:  Undefined array key "retries" in /var/www/roundcubemail/plugins/identity_switch/identity_switch_newmails.php on line 122" while reading response header from upstream, client: 127.0.0.1, server: xxx.xxx, request: "GET /plugins/identity_switch/identity_switch_newmails.php?iid=0&cache=%2Fvar%2Fwww%2Froundcubemail%2Ftemp%2Fidentity_switch_cache.rgti9f8feqdjg5p2v688kpvlrk HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "xxx.xxx"

**Comment by toteph42** [comment]
For exactly this problem I added code when loading any internal variable in `identity_switch_prefs::get()` to ensure a default value is loaded in 1.1.3 Cannot reproduce error. Assume it also caching related.
