### ISSUE TITLE
Uncaught TypeError: Cannot access offset of type string on string in

### ISSUE THREAD

**Issue by pikachurus** [toteph42/identity_switch#46]
identity_switch 1.1.3

try to login:
![image](https://github.com/user-attachments/assets/9f85dc53-c3bc-40db-966d-c6ea1e33577c)

after refresh this page (via F5), it looks normal again. 

in logs:
2024/12/07 18:47:09 [error] 1619#1619: *38659 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /var/www/roundcubemail/plugins/identity_switch/identity_switch_prefs.php:1137
Stack trace:
#0 /var/www/roundcubemail/plugins/identity_switch/identity_switch.php(264): identity_switch_prefs->set()
#1 /var/www/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(520): identity_switch->on_render_page()
#2 /var/www/roundcubemail/program/include/rcmail_output_html.php(831): rcube_plugin_api->exec_hook()
#3 /var/www/roundcubemail/program/include/rcmail_output_html.php(654): rcmail_output_html->parse()
#4 /var/www/roundcubemail/program/include/rcmail.php(296): rcmail_output_html->send()
#5 /var/www/roundcubemail/index.php(278): rcmail->action_handler()
#6 {main}
  thrown in /var/www/roundcubemail/plugins/identity_switch/identity_switch_prefs.php on line 1137" while reading response header from upstream, client: 192.168.66.111, server: xxx.xxx, request: "POST / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "xxx.xxx", referrer: "https://xxx.xxx/?_task=login"

**Comment by toteph42** [comment]
Must be fast-cgi caching error. On this line is no comparison.
