### ISSUE TITLE
with check => false, plugin shows new mails in drop-down menu

### ISSUE THREAD

**Issue by pikachurus** [toteph42/identity_switch#47]
![image](https://github.com/user-attachments/assets/7d47b8d5-98b6-490c-87fb-f8aed4ad1f80)

config.inc.php:
![image](https://github.com/user-attachments/assets/53e68eec-c045-4617-adf5-ad0037a0ce0d)

mysql tables:
![image](https://github.com/user-attachments/assets/9e1db96b-6c0c-490b-a6a4-d304b0bbe23c)

**Comment by toteph42** [comment]
Enable `debug` and check log file for `New mail check disabled - stop checking`.

**Comment by pikachurus** [comment]
> Enable `debug` and check log file for `New mail check disabled - stop checking`.

switching profiles, in logs:
![image](https://github.com/user-attachments/assets/a6344f47-f141-431f-92e1-be54344211c7)

**Comment by toteph42** [comment]
As you can see: New checking is disabled. If checking is enabled you'll something line `Starting new mail check with arguments`.
