### ISSUE TITLE
Identity Switch Add Identity

### ISSUE THREAD

**Issue by wesch3al** [toteph42/identity_switch#49]
II was able to add 3 email accounts from Bluehost which is default in the main config.inc.php.(mail.xxxxx.com)
When I try to add Gmail or Yahoo which are not imap or smtp defaults, I get an error.(imap.gmail.com or imap.mail.yahoo.com)
Do I need to modify the plugin config.inc.php so it will accept these email accounts?

**Comment by toteph42** [comment]
Hi,
you don't need to modify `config.inc.php` at all. This is useful, if you have multiple accounts on one server and you want to get defaults loaded in identity switch account configuration setting panel to make it more easy to setup accounts for your RoundCube users (e.g. adding acc1@xx.com, acc2@xx.com, acc3@xx.com).

**Comment by wesch3al** [comment]
Toteph42,
I was able to setup 3 accounts that were Bluehost accounts. I am still having problems with Gmail and Yahoo. It will not setup, keeps giving me errors and kick the accounts back. Don't understand why, these accounts are widely used.

**Comment by wesch3al** [comment]
Toteph42,
Here is the error.

connection to storage server failed.
Server Error: AUTHENTICATE PLAIN: AUTHENTICATE Invalid credentials

**Comment by toteph42** [comment]
Hi,
I cannot help you with the configuration of your IMAP/SMTP server. Please search your configuration parameters in internet.

**Comment by wesch3al** [comment]
Totrph42,
All you had to do was tell me to use an app password. I went to gmail and yahoo and generated app passwords and they finally setup. I would think you would know more about this then I do. Anyway I figured it out myself. By the way, you took it upon yourself to close this issue before it was resolved. Don't really understand that.
