### ISSUE TITLE
mailcow  PHP Fatal error:  Uncaught TypeError: Unsupported operand types: array / int in /web/rc/plugins/identity_switch/identity_switch_prefs.php:150

### ISSUE THREAD

**Issue by newsy5** [toteph42/identity_switch#51]
PHP Version 8.2.25
Linux def6eaf74553 6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) x86_64

install in mailcow
https://docs.mailcow.email/third_party/roundcube/third_party-roundcube/

PHP Fatal error:  Uncaught TypeError: Unsupported operand types: array / int in /web/rc/plugins/identity_switch/identity_switch_prefs.php:150
Stack trace:
#0 /web/rc/plugins/identity_switch/identity_switch_prefs.php(86): identity_switch_prefs->show_general_prefs(Array)
#1 /web/rc/program/lib/Roundcube/rcube_plugin_api.php(520): identity_switch_prefs->show_default_identity_prefs(Array)
#2 /web/rc/program/actions/settings/index.php(1497): rcube_plugin_api->exec_hook('preferences_lis...', Array)
#3 /web/rc/program/actions/settings/prefs_edit.php(38): rcmail_action_settings_index::user_prefs('general')
#4 /web/rc/program/include/rcmail.php(282): rcmail_action_settings_prefs_edit->run(Array)
#5 /web/rc/index.php(278): rcmail->action_handler()
#6 {main}
  thrown in /web/rc/plugins/identity_switch/identity_switch_prefs.php on line 150

**Comment by toteph42** [comment]
Hi,
please check your `interval` in `config.inc.php`. This must be an integer number. Added cast to integer in upcoming release to ensure value is stored as an `integer`.

**Comment by newsy5** [comment]
'interval' => 300,

**Comment by toteph42** [comment]
Load version 1.1.4. Whatever is specified in your RoundCube installation, it will be converted to integer. Sorry, I would be happy to help, but I cannot reproduce error in my environment.

**Comment by toteph42** [comment]
try
`// Log IMAP conversation to <log_dir>/imap.log or to syslog`
`$config['imap_debug'] = false;`
`// Log session authentication errors to <log_dir>/session or to syslog`
`$config['log_session'] = false;`
in `config/config.inc.php`
