### ISSUE TITLE
(mariadb) ERROR: [1064] You have an error in your SQL syntax

### ISSUE THREAD

**Issue by NotFluffy** [toteph42/identity_switch#52]
Roundcube Webmail 1.6.9
identity_switch 1.1.4

During the "database initialization script for identity_switch" part of activating the plugin, I get this error : 
```
Creating database schema... ERROR: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`user_id_label`(`user_id`, `label`),
    CONSTRAINT `rcod_fk_identity_user_id...' at line 20 (SQL Query: CREATE TABLE IF NOT EXISTS `rcod_identity_switch`(
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` INT(10) UNSIGNED NOT NULL,
    `iid` INT(10) UNSIGNED NOT NULL,
    `label` VARCHAR(32),
    `flags` INT NOT NULL DEFAULT 0,
    `imap_user` VARCHAR(64),
    `imap_pwd` VARCHAR(128),
    `imap_host` VARCHAR(64),
    `imap_port` SMALLINT DEFAULT 0,
    `imap_delim` CHAR(1),
    `newmail_check` SMALLINT DEFAULT 300,
    `notify_timeout` SMALLINT DEFAULT 10,
    `smtp_host` VARCHAR(64),
    `smtp_port` SMALLINT DEFAULT 0,
    `drafts` VARCHAR(64) DEFAULT '',
    `sent` VARCHAR(64) DEFAULT '',
    `junk` VARCHAR(64) DEFAULT '',
    `trash` VARCHAR(64) DEFAULT '',
    UNIQUE rcod_KEY `user_id_label`(`user_id`, `label`),
    CONSTRAINT `rcod_fk_identity_user_id` FOREIGN KEY(`user_id`) REFERENCES `rcod_users`(`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `rcod_fk_identity_identity_id` FOREIGN KEY(`iid`) REFERENCES `rcod_identities`(`identity_id`) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(`id`),
    INDEX `rcod_IX_identity_switch_user_id`(`user_id`),
    INDEX `rcod_IX_identity_switch_iid`(`iid`)
))
[FAILED]
ERROR: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`user_id_label`(`user_id`, `label`),
    CONSTRAINT `rcod_fk_identity_user_id...' at line 20
```

I went to my database and removing the "rcod_KEY", the table was able to be created (manually), but the activation still gets stuck on the same error.

**Comment by toteph42** [comment]
Which database does you use and which version is it?

**Comment by NotFluffy** [comment]
Oops forgot to write it : Mariadb version 10.6.19

**Comment by toteph42** [comment]
Hmm... I'm not sure how to solve:

`config.inc.php.sample` states:
`// Currently supported db_providers: mysql, pgsql, sqlite, mssql, sqlsrv, oracle`

Seems RoundCube does not support mariadb. So there is no selector available to create mariadb SQL files even if I create mariadb conform SQL files.

**Comment by toteph42** [comment]
Can't fix problem for you.

The problem is not related to `identity_switch` plugin. During creation of database table, there two references to other tables were created: Table `users` must contain a field named `user_id`. This field must be of type `PRIMARY KEY`. The other table is `identities`. There must be a field named `identity_id`  also defined as `PRIMARY KEY`. Both were RoundCube tables. You should check and adjust the definition of there fields.

**Comment by NotFluffy** [comment]
As written in my first post, the only thing that blocks the creation of the unique key is "rcod_KEY".

The creation of the unique key works if that section is taken off like so : 
''"UNIQUE `user_id_label`(`user_id`, `label`)'''

is the "rcod_KEY" really necessary for the table? I cannot find it's use anywhere

**Comment by NotFluffy** [comment]
The problem was KEY not rcod*

 "UNIQUE KEY" does not seem to work, but "UNIQUE" works
If I use ``` UNIQUE `user_id_label`(`user_id`, `label`)```, it creates the table without problem. 

*rcod is the prefix for my roundcube databases (I need to sleep more, it was taking me for a loop)

**Comment by toteph42** [comment]
Update in 1.1.7
